### ISSUE TITLE
is that possible to deploy Tell on Ethernet 

### ISSUE THREAD

**Issue by theta1990** [tellproject/tell#1]
Hi, I want to conduct some experiments. But I do not have a cluster equipped with RDMA. Is that possible to deploy Tell on Ethernet netowrk?

**Comment by mpilman** [comment]
Currently, Tell does not support ethernet. In the long run, we would like to add Ethernet support to crossbow infinio (the network library Tell uses), but this will require some major refactoring.

One thing that should work is Soft RoCE: https://github.com/SoftRoCE which is a software implementation of Infiniband. SoftRoCE is AFAIK not feature complete, but it should support all features that Tell needs.

**Comment by theta1990** [comment]
Thanks a lot! I will try right now.
